Php 7.4
mobtitude/zendframework1 pull request #7
Opened 2021-09-29 14:38 UTC by MasterSalomon

2021-09-30 17:49 UTC, pszalko requested changes
Poprawić komentarze

2021-09-30 17:49 UTC, pszalko commented on composer.json
> -        "php": ">=5.2.11"
Usunąć to wymaganie, przecież 5.2.11 będzie OK.

2021-09-30 17:49 UTC, pszalko commented on composer.json
> -        "php-7.2"
Zostawić 7.2, to tylko keywords.
Dodać nową wersję.

2021-09-30 17:49 UTC, pszalko commented on library/Zend/Cloud/Infrastructure/Adapter/Ec2.php
> -            $this->ec2Zone = new Zend_Service_Amazon_Ec2_AvailabilityZones($this->accessKey,$this->accessSecret,$this->region);
Nazwa pliku zgadza się z nazwą klasy po zmianie?

2021-09-30 17:49 UTC, pszalko commented on library/Zend/Measure/Cooking/Volume.php
> -        'CAN_2POINT5'       => array(array('' => '0.0037854118', '/' => '16', '' => '3.5'), '2.5th can'),
Dlaczego taka modyfikacja? Zniknął wpis `''`

2021-09-30 17:49 UTC, pszalko commented on library/Zend/Measure/Cooking/Weight.php
> -        'TEASPOON'      => array(array('' => '1.2503332', '' => '453.59237', '/' => '128'), 'tsp'),
Błędne zmiany w plikach?

2021-09-30 17:49 UTC, pszalko commented on library/Zend/Registry.php
> -     * Workaround for http://bugs.php.net/bug.php?id=40442 (ZF-960).
Sprawdzić w jakiej wersji PHP poprawiono ten błąd i w composer ustawić tą wersję jako minimalną.

2021-09-30 17:49 UTC, pszalko commented on library/Zend/Rest/Route.php
> -    public function assemble($data = array(), $reset = false, $encode = true)
Skąd wynika dodanie parametru `$partial`?

2021-09-30 17:49 UTC, pszalko commented on library/Zend/Service/Console/Command.php
> -				$handlerDescription = isset($handlerDescriptions[$hi]) ? $handlerDescriptions[$hi] : isset($handlerDescriptions[0]) ? $handlerDescriptions[0] : '';
Chyba złe nawiasowanie? Nie powinno być `(isset ? x : (isset ? y : z))`

2021-10-01 10:40 UTC, MasterSalomon commented on library/Zend/Rest/Route.php
> -    public function assemble($data = array(), $reset = false, $encode = true)
Z klasy po której dziedziczy. Jest po prostu inna definicja funkcji.

2021-10-01 10:40 UTC, MasterSalomon commented on library/Zend/Cloud/Infrastructure/Adapter/Ec2.php
> -            $this->ec2Zone = new Zend_Service_Amazon_Ec2_AvailabilityZones($this->accessKey,$this->accessSecret,$this->region);
Tak

2021-10-01 10:48 UTC, MasterSalomon commented on library/Zend/Service/Console/Command.php
> -				$handlerDescription = isset($handlerDescriptions[$hi]) ? $handlerDescriptions[$hi] : isset($handlerDescriptions[0]) ? $handlerDescriptions[0] : '';
Tak

2021-10-01 10:50 UTC, MasterSalomon commented on library/Zend/Measure/Cooking/Volume.php
> -        'CAN_2POINT5'       => array(array('' => '0.0037854118', '/' => '16', '' => '3.5'), '2.5th can'),
Duplikacja wpisu z pustym kluczem ''. Pierwsza wartość zostanie pominięta przy tworzeniu tablicy.

2021-10-01 10:50 UTC, MasterSalomon commented on library/Zend/Measure/Cooking/Weight.php
> -        'TEASPOON'      => array(array('' => '1.2503332', '' => '453.59237', '/' => '128'), 'tsp'),
Duplikacja wpisu z pustym kluczem ''. Pierwsza wartość zostanie pominięta przy tworzeniu tablicy.

2021-10-01 11:05 UTC, MasterSalomon commented on library/Zend/Registry.php
> -     * Workaround for http://bugs.php.net/bug.php?id=40442 (ZF-960).
https://www.php.net/ChangeLog-5.php

Rozwiązano w 5.2.2

2021-10-01 11:15 UTC, pszalko approved these changes

2021-10-01 11:16 UTC, merged